Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/config/routes.rb
Blackbelt::Application.routes.draw do

  resources :users
  resources :sessions
  resources :posts do
    resources :likes
  end

end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :likes
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name, presence: true,
							length: {within: 2..50}

	validates :last_name, presence: true,
							length: {within: 2..50}
	
	validates :email, presence: true,
						format: {with: EMAIL_REGEX, message: "incorrect email format"},
						uniqueness: {case_sensitive: false}
	
	validates :password, presence: true,
							length: {within: 6..20}

	before_save {self.email = email.downcase}
	has_secure_password
	has_many :posts
	has_many :likes
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		if (Like.where(user_id: session[:user_id], post_id: params[:post_id])).count > 0
			redirect_to :back, notice: "You already liked this post."
		else
			@like = Like.new
			@like.user_id = session[:user_id]
			@like.post_id = params[:post_id]
			@like.save
	    	redirect_to :back, notice: "Your like was successfully recorded."
	    end
    end
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.find(:all).sort {|x,y| y.likes.count <=> x.likes.count}
  	@post=Post.new
  end

  def new
  end

  def create
  	@post = Post.new(post_params)
    @post.save
    redirect_to :back
  end

  def show

  	@posts = Post.find(params[:id])
  	@likes = @post.likes
  end

  private
  	def post_params
  		params.require(:post).permit(:content, :user_id)
  	end

end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	# user = User.find_by(email: params[:user][:email]).try(:authenticate, params[:user][:password])
  	# if email address is blank
  	if params[:session][:email].blank?
  		flash[:errors_login] = "Email must not be blank"
  		redirect_to :back
  	# if email address does not exist in database
  	elsif User.find_by(email: params[:session][:email]).nil?
  		flash[:errors_login] = "A user with this email address does not exist in the database"
		redirect_to :back
  	# if email address exists in the database but password does not match
  	elsif !(User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password]))
  		# redirect_to new_user_path, :flash => { :error => 'Email and password don\'t match.' }
  		flash[:errors_login] = "Email and password do not match"
  		redirect_to :back
  	# otherwise, email address and password match -> success!
  	else
      user = User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password])
  		sign_in user
		  redirect_to users_path
  	end
  end

  def destroy
    sign_out
    redirect_to users_path
  end
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		redirect_to users_path, notice: "User was successfully created."
  	else
  		flash[:errors_register] = @user.errors.full_messages
      	redirect_to :back
  	end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/helpers/likes_helper.rb
module LikesHelper
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/helpers/posts_helper.rb
module PostsHelper
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  # setter method
  def current_user=(user)
    @current_user = user
  end

  # getter method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user 
  end

  def deny_access
    redirect_to welcome_path, :notice => "Please sign in to access this page."
  end

end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/helpers/users_helper.rb
module UsersHelper
end

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/views/posts/index.html.erb
<div class="container">
	<h1>Bright Ideas</h1>

	<% if signed_in? %>
		<p class='success'>Welcome, <%= current_user.first_name %>!</p>
		<p><%= link_to 'Logout', session_path(current_user), method: :delete, class: 'btn btn-primary' %></p>

		<hr>

		<h3>Post a Bright Idea!</h3>
		<%= simple_form_for @post do |f| %>
			<%=f.input :content, label: false, placeholder: 'Post something witty...' %>
			<%=f.input :user_id, as: :hidden, input_html: { value: session[:user_id] } %>
			<%=f.button :submit, 'Post', class: 'btn btn-success' %>
		<% end %>
	<% else %>
		<p class='error'>Please register or login to post a bright idea or to "like" a bright idea.</p>
		<p><%= link_to 'Register', new_user_path, class: 'btn btn-primary', id: 'register' %></p>
		<p><%= link_to 'Login', new_session_path, class: 'btn btn-primary' %></p>
	<% end %>

	<hr>

	<p class='notice'><%= notice %></p>
	<% @posts.each do |post| %>
		<div class="row">
			<div class="col-md-2 bold"> <a href="/users/<%= post.user.id %>"><%= post.user.first_name %></a> says:</div>
			<div class="col-md-6"><%= post.content %></div>
		</div>
		<div class="row">
			<div class="col-md-2"></div>
				<% if signed_in? %>
					<div class="col-md-1 likes">
						<%= button_to 'Like', post_likes_path(post) %>
					</div>
				<% end %>
			<div class="col-md-3">
				<%= link_to post.likes.count.to_s + ' people', post_path(post) %> like this.
			</div>
		</div>
	<% end %>




</div>

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

Ruby/4-first_vagrant_box/CodingDojo Black Belt/Bright-ideas/app/views/posts/show.html.erb
<div class="container">
	<h2>Bright Idea</h2>
	<div class="row post">
		<div class="col-md-2 bold"><%= @post.user.first_name %> says:</div>
		<div class="col-md-6"><%= @post.content %></div>
	</div>

	<p>People who liked this post:</p>

	<table>
		<thead>
			<tr>
				<th>User ID</th>
				<th>Name</th>
				<th>Email</th>
			</tr>
		</thead>
		<tbody>
			<% @likes.each do |like| %>
				<tr>
					<td><%= like.user_id %></td>
					<td><%= like.user.first_name + ' ' + like.user.last_name %></td>
					<td><%= like.user.email %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'Back to Bright Ideas', posts_path %>



</div>